### ISSUE TITLE
Cosas varias

### ISSUE THREAD

**Issue by angabar** [pbalbores/plantilla_web#1]
Hola Pepe!

Me alegra ver que vas investigando en el `background-image`. Bien, voy a intentar aclarar los puntos que comentas en el email:

#### Header
Lo has preparado de manera casi perfecta, tan solo te faltaría el posicionamiento del contenido con respecto al elemento, la propiedad `background-position` investiga un poco sobre esta y sus propiedades y verás como lo consigues.

#### Cuerpo
Las etiquetas están bien, pero si te fijas en la línea 24 del HTML tienes lo siguiente:
```
<div class="contenido"></div>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat necessitatibus illum tempore, quas rem repellendus temporibus aut molestiae asperiores fuga neque totam similique cum illo enim vitae! Accusamus, vero esse?</p>
```

Como ves, el párrafo está fuera del contenedor con la clase `contenido` por lo que no aplicará las clases que pongas en este. Simplemente coloca el párrafo dentro del contenedor y listo.

#### Márgenes globales
Esta es una cosa que he visto yo, y es que por defecto el navegador pone un `margin` al contenido de nuestro HTML, por lo que sale como una separación blanca en todo el documento. Esto lo puedes solucionar así:

```
* {
  margin: 0px;
}
```

Todo lo demás va bien, te dejo que sigas trabajando e investigando los diferentes puntos del ejercicio. Si tienes alguna duda, coméntame.

**Comment by pbalbores** [comment]
Muchas gracias. 
Lo del DIV me dió bastante la lata. Es por falta de práctica con el VisualStudioCode ya que crea automaticamente las etiquetas de cierre ;) ;).
Por la tarde avancé bastante. 
Me queda pendiente el tema de la imagen del Header, de conseguir que las imágenes de las Cards tengan las esquinas superiores redondeadas y de colocar bien los contenidos del NavBar.

**Comment by angabar** [comment]
Lo de los bordes de las imágenes es un poco rebuscado, como pista te diré que `border-radius` puede recibir un único valor, que aplicará a todas las esquinas, o 4 valores, correspondientes a cada una de las esquinas.

Ya me dices.

**Comment by pbalbores** [comment]
Hola, creo que ya está practicamente acabada. 
Te comento algunas dudas:
1. A la imagen de cabecera le apliqué un height de 400px y queda más o menos como la del ejemplo. La duda es que que la ajusta en horizontal pero con resoluciones altas la imagen horizontalmente no ocupa la totalidad de la pantalla. 
2. A las imágenes de cards se les asigna una class y se les aplica un border radius en las esquinas superiores. Quedan bien. La duda es porque no se les aplica el border-radius del contenedor en el que están.
3. El cuerpo tiene un display:flex, con wrap y justify-content:center. Esto hace que la última card no quepa en la misma línea que le resto y quede sola centrada en una línea inferior. Está bién así o debería ir a la derecha?
4. Navbar. Tiene un justify-content: space-between, con un padding de 100px;. Entiendo que debería centrar los elementos manteniendo espacio entre ellos y aplicando el padding de 100px en cada extremo. Creo que en mi caso aplica el padding en el lado izquierdo pero no en el derecho ya que no ajusta la última opción del menú a la derecha.
Saludos y muchas gracias
Saludos y gracias

**Comment by angabar** [comment]
Buenas tardes Pepe!

Te comento a continuación todos los puntos:

1. Está perfecto, tan solo te falta la propiedad que se encarga de hacer que la imagen cubra todo el contenedor `background-size: cover;` y ya te saldría.

2. Porque las imágenes van a su bola, les da igual el `border-radius` del contenedor, tenemos que aplicar uno específicamente sobre ellas si queremos que tengan uno.

3. Si, así está perfecto! ;)

4. Aquí hay un par de cosas que si quería comentarte, en primer lugar tienes una etiqueta `h4` mal cerrada haciendo que ocupe un espacio innecesario en el `navbar`, fíjate en la linea 22 del documento HTML:

```
<div class="navbar">
  <h4>Inicio</h4>
  <h4>Ofertas</h4>
  <h4>Quienes somos</h4>
  <h4>Contacto<h4>      
</div>
```

Como ves, "Contacto" no está cerrada, lo que hace que el navegador piense que existen dos etiquetas en lugar de una. Ciérrala convenientemente y así el `navbar` dejará de tener ese espacio a la derecha.

Luego hay otra cosa que veo, y es ese `padding: 100px`, prueba a eliminarlo y a modificar la distribución de elementos en el `navbar` de `space-between` a `space-around`, y ya lo tendrías.

Espero haberte ayudado, si tienes cualquier otra duda, por favor, házmelo saber. Que vaya bien!

**Comment by pbalbores** [comment]
Perfecto, muchas gracias.
Ya subí a Github los archivos con las corecciones que propones.

**Comment by angabar** [comment]
Está perfecto Pepe! Enhorabuena!
